Adapted from https://johnwlambert.github.io/conv-backprop/

In [13]:
import numpy as np
import torch

In [95]:
# Imagine a simple 3x3 kernel k (Sobel filter…):

k = np.array(
    [
        [1,0,-1],
        [2,0,-2],
        [1,0,-1]
    ]).reshape(1,1,3,3).astype(np.float32)
k2 = np.array(
    [
        [.1,.2 ],
        [.3,.4]
    ]
).reshape(1,1,2,2).astype(np.float32)
k2


array([[[[0.1, 0.2],
         [0.3, 0.4]]]], dtype=float32)

In [85]:
# 6x5 input image

x = np.array(
    [
        [1,1,1,2,3],
        [1,1,1,2,3],
        [1,1,1,2,3],
        [2,2,2,2,3],
        [3,3,3,3,3],
        [4,4,4,4,4]
    ]).reshape(1,1,6,5).astype(np.float32)

In [91]:
# perform cross-correlation of x with k:

conv = torch.nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3,
    bias=False,
    stride = 1,
    padding_mode='zeros',
    padding=0
)

conv2 = torch.nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3,
    bias=False,
    stride = 1,
    padding_mode='zeros',
    padding=0
)

x_tensor = torch.from_numpy(x)
x_tensor.requires_grad = True
conv.weight = torch.nn.Parameter(torch.from_numpy(k))
out = conv(x_tensor)
# out = conv2(out)


# create a scalar loss, and perform backprop:

loss = out.sum()
loss.backward()

print(conv.weight.grad)

print(x_tensor.grad)


tensor([[[[15., 18., 25.],
          [21., 23., 28.],
          [30., 31., 34.]]]])
tensor([[[[ 1.,  1.,  0., -1., -1.],
          [ 3.,  3.,  0., -3., -3.],
          [ 4.,  4.,  0., -4., -4.],
          [ 4.,  4.,  0., -4., -4.],
          [ 3.,  3.,  0., -3., -3.],
          [ 1.,  1.,  0., -1., -1.]]]])


In [77]:

conv_t = torch.nn.Conv2d(2, 28, 3, stride=1)

input = torch.randn(20, 2, 50, 50)

output = conv_t(input)

In [97]:
import torch
import torch.nn as nn
import numpy as np

# Define a synthetic grayscale image (1 channel) with size 8x8
image_size = 8
input_image = torch.rand(1, 1, image_size, image_size)  # Batch size of 1
display(input_image)


# Define two convolutional layers with different numbers of output filters
# Both using kernel size of 3, stride of 1, and no padding
conv_layer_1 = nn.Conv2d(in_channels=1, out_channels=2, kernel_size=3, stride=1, padding=0)
conv_layer_2 = nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, stride=1, padding=0)

# Apply the first convolutional layer
output1 = conv_layer_1(input_image)
print("Output shape with 2 filters:", output1.shape)  # Expect (1, 2, 6, 6)

# Apply the second convolutional layer
output2 = conv_layer_2(input_image)
print("Output shape with 5 filters:", output2.shape)  # Expect (1, 5, 6, 6)

tensor([[[[0.2139, 0.8752, 0.2312, 0.7534, 0.5673, 0.5537, 0.0543, 0.5359],
          [0.3636, 0.7236, 0.6165, 0.3362, 0.0806, 0.7882, 0.9486, 0.2066],
          [0.3456, 0.9012, 0.7034, 0.0886, 0.5687, 0.1479, 0.1860, 0.7754],
          [0.1797, 0.9649, 0.7833, 0.0344, 0.5585, 0.7828, 0.7037, 0.1571],
          [0.7592, 0.6711, 0.5788, 0.4862, 0.2801, 0.8108, 0.2283, 0.2222],
          [0.0980, 0.1451, 0.9338, 0.9618, 0.6654, 0.9033, 0.8026, 0.8916],
          [0.2584, 0.0916, 0.1655, 0.1650, 0.3840, 0.5716, 0.7292, 0.4002],
          [0.3176, 0.0804, 0.5832, 0.3526, 0.4573, 0.4736, 0.4673, 0.8424]]]])

Output shape with 2 filters: torch.Size([1, 2, 6, 6])
Output shape with 5 filters: torch.Size([1, 5, 6, 6])
